/* USER CODE BEGIN Header */
/**

  ******************************************************************************

  * @file           : main.c
  * @brief          : Main program body
  * Project         : EE 329 A1 Assignments 1a, 1b
  * Authors         : Jordan Reichhardt -jordan.reichhardt@gmail.com
  * Blame           : Bryce Paulson(classmate), ChatGPT
  * Version         : 4
  * Date            : 9/29/24
  ******************************************************************************

  * Plan: INSTRUCTION TIMING & LED COUNTING
  * 1. Count to 15 in binary on LEDs
  * Iterate through this 3 times then start execution timing

  ******************************************************************************
  LED wiring:
  *PC0- A1 (LSB)
  *PC1- A3
  *PC2- A7
  *PC3- A4
  */

/* USER CODE END Header */
#include <math.h>
#include "main.h"
#include <stdint.h>
#include <time.h>  // For clock()

typedef uint8_t var_type;  // Define var_type (uint8_t)

//configure functions to be used before defined fully
void SystemClock_Config(void);
var_type TestFunction(var_type num);
void delay(int count);  // allows delay to be used before delay is defined

int main(void) {  // main should return int and doesn't take any parameters
    var_type main_int = 0;
    int iterations = 0;

    SystemClock_Config();  // Configure the system clock
    HAL_Init();  // Initialize the HAL library

    // Enable GPIOC clock and configure pins PC0-PC3 as output for LEDS to turn on
    RCC->AHB2ENR |= (RCC_AHB2ENR_GPIOCEN);  // allow GPIOC clock to turn on
    GPIOC->MODER &= ~(GPIO_MODER_MODE0 | GPIO_MODER_MODE1 | GPIO_MODER_MODE2 | GPIO_MODER_MODE3);  // Clear mode for pc0-pc3
    GPIOC->MODER |= (GPIO_MODER_MODE0_0 | GPIO_MODER_MODE1_0 | GPIO_MODER_MODE2_0 | GPIO_MODER_MODE3_0);  // Set to output mode for pc0-pc3
    GPIOC->OTYPER &= ~(GPIO_OTYPER_OT0 | GPIO_OTYPER_OT1 | GPIO_OTYPER_OT2 | GPIO_OTYPER_OT3);  // Set to push-pull for pc0- pc3
    GPIOC->PUPDR &= ~(GPIO_PUPDR_PUPD0 | GPIO_PUPDR_PUPD1 | GPIO_PUPDR_PUPD2 | GPIO_PUPDR_PUPD3);  // No pull-up, no pull-down for pc0-pc3
    GPIOC->OSPEEDR |= ((3 << GPIO_OSPEEDR_OSPEED0_Pos) |
                       (3 << GPIO_OSPEEDR_OSPEED1_Pos) |
                       (3 << GPIO_OSPEEDR_OSPEED2_Pos) |
                       (3 << GPIO_OSPEEDR_OSPEED3_Pos));  // Initialize at a high speed
    GPIOC->BRR = (GPIO_PIN_0 | GPIO_PIN_1 | GPIO_PIN_2 | GPIO_PIN_3);  // Turn off all LEDs pc0-pc3

    /* Infinite loop */
    while (1) {
        main_int++;  // Increment main int variable

        // Iterate through led_count to handle GPIO pin manipulation
        for (int led_add = 0; led_add < 16; led_add++) { //this loop generated by chatgpt
            // Reset all pins (turn off all LEDs)
            GPIOC->BRR = (GPIO_PIN_0 | GPIO_PIN_1 | GPIO_PIN_2 | GPIO_PIN_3);

            // Set individual pins based on the count value
            if (led_add & 0x1) GPIOC->BSRR = GPIO_PIN_0;  // turn on PC0 led if bit 0 is set
            if (led_add & 0x2) GPIOC->BSRR = GPIO_PIN_1;  // turn on PC1 led if bit 1 is set
            if (led_add & 0x4) GPIOC->BSRR = GPIO_PIN_2;  // turn on PC2 led if bit 2 is set
            if (led_add & 0x8) GPIOC->BSRR = GPIO_PIN_3;  // turn on PC3 led if bit 3 is set

            // Delay so LEDs can be seen changing between bits
            delay(100000);
        }

        // Increment the iterations
        iterations++;

        // After 3 iterations, set pin 0, call the TestFunction, and then reset pin 0
        if (iterations >= 3) {
            GPIOC->BRR = (GPIO_PIN_2 | GPIO_PIN_3);

            while (1) {
                GPIOC->BSRR = GPIO_PIN_0;
                TestFunction(main_int);
                GPIOC->BRR = GPIO_PIN_0;
            }
        }
    }
}

var_type TestFunction(var_type num) {
    var_type test_var;  // assigns var_type as test_var which is a local variable
    GPIOC->BSRR = GPIO_PIN_1;  // Set PC1 high
    test_var = num * 3;  // Increment the input number
    GPIOC->BRR = GPIO_PIN_1;  // Set PC1 low

    return test_var;  // Return the modified value
}

void delay(int count) {  // delay num is the number of CPU cycles to wait
    for (int delay_num = 0; delay_num < count; delay_num++) {
        __NOP(); // no operation
    }
}

void SystemClock_Config(void) {
    // Implementation of system clock configuration
}
